#include "HistogramManager.h"

#include <TH2.h>
#include <TFile.h>
#include <iostream>
#include <iomanip> 
#include <fstream>
#include <TTree.h>

HistogramManager::HistogramManager(std::string FILE){

  m_FileName=FILE;
  std::string FILE_NAME=m_FileName+"_Histgram.root";
  std::cout<<"Create New File="<<FILE_NAME<<std::endl;
  file= new TFile(FILE_NAME.c_str(),"recreate");

  //TTree
  m_tree = new TTree("physics","physics");

  //Event Information
  m_tree->Branch("eventnumber",&eventnumber,"eventnumber/I");
  m_tree->Branch("bcid",&bcid,"bcid/I");

  //Offline
  m_tree->Branch("muon_n",&muon_n,"muon_n/I");
  muon_pt=new std::vector<float>; m_tree->Branch("muon_pt",&muon_pt);
  muon_eta=new std::vector<float>; m_tree->Branch("muon_eta",&muon_eta);
  muon_phi=new std::vector<float>; m_tree->Branch("muon_phi",&muon_phi);
  muon_m=new std::vector<float>; m_tree->Branch("muon_m",&muon_m);
  muon_charge=new std::vector<int>; m_tree->Branch("muon_charge",&muon_charge);
  muon_author=new std::vector<int>; m_tree->Branch("muon_author",&muon_author);
  muon_Type=new std::vector<int>; m_tree->Branch("muon_Type",&muon_Type);

  //Museg
  m_tree->Branch("museg_n",&museg_n,"museg_n/I");
  museg_x=new std::vector<float>; m_tree->Branch("museg_x",&museg_x);
  museg_y=new std::vector<float>; m_tree->Branch("museg_y",&museg_y);
  museg_z=new std::vector<float>; m_tree->Branch("museg_z",&museg_z);
  museg_px=new std::vector<float>; m_tree->Branch("museg_px",&museg_px);
  museg_py=new std::vector<float>; m_tree->Branch("museg_py",&museg_py);
  museg_pz=new std::vector<float>; m_tree->Branch("museg_pz",&museg_pz);
  museg_t0=new std::vector<float>; m_tree->Branch("museg_t0",&museg_t0);
  museg_t0error=new std::vector<float>; m_tree->Branch("museg_t0error",&museg_t0error);
  museg_chi2=new std::vector<float>; m_tree->Branch("museg_chi2",&museg_chi2);
  museg_ndof=new std::vector<float>; m_tree->Branch("museg_ndof",&museg_ndof);
  museg_sector=new std::vector<int>; m_tree->Branch("museg_sector",&museg_sector);
  museg_stationName=new std::vector<int>; m_tree->Branch("museg_stationName",&museg_stationName);
  museg_stationEta=new std::vector<int>; m_tree->Branch("museg_stationEta",&museg_stationEta);
  museg_author=new std::vector<int>; m_tree->Branch("museg_author",&museg_author);

  //Extrapolate
  m_tree->Branch("ext_mu_n",&ext_mu_n,"ext_mu_n/I");
  ext_mu_type=new std::vector<int>; m_tree->Branch("ext_mu_type",&ext_mu_type);
  ext_mu_index=new std::vector<int>; m_tree->Branch("ext_mu_index",&ext_mu_index);
  ext_mu_size=new std::vector<int>; m_tree->Branch("ext_mu_size",&ext_mu_size);
  ext_mu_targetVec=new std::vector<std::vector<int>>; m_tree->Branch("ext_mu_targetVec",&ext_mu_targetVec);
  ext_mu_targetDistanceVec=new std::vector<std::vector<float>>; m_tree->Branch("ext_mu_targetDistanceVec",&ext_mu_targetDistanceVec);
  ext_mu_targetEtaVec=new std::vector<std::vector<float>>; m_tree->Branch("ext_mu_targetEtaVec",&ext_mu_targetEtaVec);
  ext_mu_targetPhiVec=new std::vector<std::vector<float>>; m_tree->Branch("ext_mu_targetPhiVec",&ext_mu_targetPhiVec);
  ext_mu_targetDeltaEtaVec=new std::vector<std::vector<float>>; m_tree->Branch("ext_mu_targetDeltaEtaVec",&ext_mu_targetDeltaEtaVec);
  ext_mu_targetDeltaPhiVec=new std::vector<std::vector<float>>; m_tree->Branch("ext_mu_targetDeltaPhiVec",&ext_mu_targetDeltaPhiVec);
  ext_mu_targetPxVec=new std::vector<std::vector<float>>; m_tree->Branch("ext_mu_targetPxVec",&ext_mu_targetPxVec);
  ext_mu_targetPyVec=new std::vector<std::vector<float>>; m_tree->Branch("ext_mu_targetPyVec",&ext_mu_targetPyVec);
  ext_mu_targetPzVec=new std::vector<std::vector<float>>; m_tree->Branch("ext_mu_targetPzVec",&ext_mu_targetPzVec);

  //TGCPRD
  m_tree->Branch("TGC_prd_n",&TGC_prd_n,"TGC_prd_n/I");
  TGC_prd_x=new std::vector<float>; m_tree->Branch("TGC_prd_x",&TGC_prd_x);
  TGC_prd_y=new std::vector<float>; m_tree->Branch("TGC_prd_y",&TGC_prd_y);
  TGC_prd_z=new std::vector<float>; m_tree->Branch("TGC_prd_z",&TGC_prd_z);
  TGC_prd_shortWidth=new std::vector<float>; m_tree->Branch("TGC_prd_shortWidth",&TGC_prd_shortWidth);
  TGC_prd_longWidth=new std::vector<float>; m_tree->Branch("TGC_prd_longWidth",&TGC_prd_longWidth);
  TGC_prd_length=new std::vector<float>; m_tree->Branch("TGC_prd_length",&TGC_prd_length);
  TGC_prd_isStrip=new std::vector<int>; m_tree->Branch("TGC_prd_isStrip",&TGC_prd_isStrip);
  TGC_prd_gasGap=new std::vector<int>; m_tree->Branch("TGC_prd_gasGap",&TGC_prd_gasGap);
  TGC_prd_channel=new std::vector<int>; m_tree->Branch("TGC_prd_channel",&TGC_prd_channel);
  TGC_prd_eta=new std::vector<int>; m_tree->Branch("TGC_prd_eta",&TGC_prd_eta);
  TGC_prd_phi=new std::vector<int>; m_tree->Branch("TGC_prd_phi",&TGC_prd_phi);
  TGC_prd_station=new std::vector<int>; m_tree->Branch("TGC_prd_station",&TGC_prd_station);
  TGC_prd_bunch=new std::vector<int>; m_tree->Branch("TGC_prd_bunch",&TGC_prd_bunch);

  //RPCRPD
  m_tree->Branch("RPC_prd_n",&RPC_prd_n,"RPC_prd_n/I");
  RPC_prd_x=new std::vector<float>; m_tree->Branch("RPC_prd_x",&RPC_prd_x);
  RPC_prd_y=new std::vector<float>; m_tree->Branch("RPC_prd_y",&RPC_prd_y);
  RPC_prd_z=new std::vector<float>; m_tree->Branch("RPC_prd_z",&RPC_prd_z);
  RPC_prd_x2=new std::vector<float>; m_tree->Branch("RPC_prd_x2",&RPC_prd_x2);
  RPC_prd_y2=new std::vector<float>; m_tree->Branch("RPC_prd_y2",&RPC_prd_y2);
  RPC_prd_z2=new std::vector<float>; m_tree->Branch("RPC_prd_z2",&RPC_prd_z2);
  RPC_prd_time=new std::vector<float>; m_tree->Branch("RPC_prd_time",&RPC_prd_time);
  RPC_prd_triggerInfo=new std::vector<int>; m_tree->Branch("RPC_prd_triggerInfo",&RPC_prd_triggerInfo);
  RPC_prd_ambiguityFlag=new std::vector<int>; m_tree->Branch("RPC_prd_ambiguityFlag",&RPC_prd_ambiguityFlag);
  RPC_prd_measuresPhi=new std::vector<int>; m_tree->Branch("RPC_prd_measuresPhi",&RPC_prd_measuresPhi);
  RPC_prd_inRibs=new std::vector<int>; m_tree->Branch("RPC_prd_inRibs",&RPC_prd_inRibs);
  RPC_prd_station=new std::vector<int>; m_tree->Branch("RPC_prd_station",&RPC_prd_station);
  RPC_prd_stationEta=new std::vector<int>; m_tree->Branch("RPC_prd_stationEta",&RPC_prd_stationEta);
  RPC_prd_stationPhi=new std::vector<int>; m_tree->Branch("RPC_prd_stationPhi",&RPC_prd_stationPhi);
  RPC_prd_doubletR=new std::vector<int>; m_tree->Branch("RPC_prd_doubletR",&RPC_prd_doubletR);
  RPC_prd_doubletZ=new std::vector<int>; m_tree->Branch("RPC_prd_doubletZ",&RPC_prd_doubletZ);
  RPC_prd_stripWidth=new std::vector<double>; m_tree->Branch("RPC_prd_stripWidth",&RPC_prd_stripWidth);
  RPC_prd_stripLength=new std::vector<double>; m_tree->Branch("RPC_prd_stripLength",&RPC_prd_stripLength);
  RPC_prd_gasGap=new std::vector<int>; m_tree->Branch("RPC_prd_gasGap",&RPC_prd_gasGap);
  RPC_prd_channel=new std::vector<int>; m_tree->Branch("RPC_prd_channel",&RPC_prd_channel);

  //Tile
  m_tree->Branch("TILE_murcv_trig_n",&TILE_murcv_trig_n,"TILE_murcv_trig_n/I");
  TILE_murcv_trig_mod=new std::vector<int>; m_tree->Branch("TILE_murcv_trig_mod",&TILE_murcv_trig_mod);
  TILE_murcv_trig_part=new std::vector<int>; m_tree->Branch("TILE_murcv_trig_part",&TILE_murcv_trig_part);
  TILE_murcv_trig_bit0=new std::vector<bool>; m_tree->Branch("TILE_murcv_trig_bit0",&TILE_murcv_trig_bit0);
  TILE_murcv_trig_bit1=new std::vector<bool>; m_tree->Branch("TILE_murcv_trig_bit1",&TILE_murcv_trig_bit1);
  TILE_murcv_trig_bit2=new std::vector<bool>; m_tree->Branch("TILE_murcv_trig_bit2",&TILE_murcv_trig_bit2);
  TILE_murcv_trig_bit3=new std::vector<bool>; m_tree->Branch("TILE_murcv_trig_bit3",&TILE_murcv_trig_bit3);
  m_tree->Branch("TILE_murcv_raw_n",&TILE_murcv_raw_n,"TILE_murcv_raw_n/I");
  TILE_murcv_raw_count=new std::vector<float>; m_tree->Branch("TILE_murcv_raw_count",&TILE_murcv_raw_count);
  TILE_murcv_raw_energy=new std::vector<float>; m_tree->Branch("TILE_murcv_raw_energy",&TILE_murcv_raw_energy);
  TILE_murcv_raw_ros=new std::vector<int>; m_tree->Branch("TILE_murcv_raw_ros",&TILE_murcv_raw_ros);
  TILE_murcv_raw_drawer=new std::vector<int>; m_tree->Branch("TILE_murcv_raw_drawer",&TILE_murcv_raw_drawer);
  TILE_murcv_raw_channel=new std::vector<int>; m_tree->Branch("TILE_murcv_raw_channel",&TILE_murcv_raw_channel);
  m_tree->Branch("TILE_murcv_digit_n",&TILE_murcv_digit_n,"TILE_murcv_digit_n/I");
  TILE_murcv_digit_nSamples=new std::vector<int>; m_tree->Branch("TILE_murcv_digit_nSamples",&TILE_murcv_digit_nSamples);
  TILE_murcv_digit_ros=new std::vector<int>; m_tree->Branch("TILE_murcv_digit_ros",&TILE_murcv_digit_ros);
  TILE_murcv_digit_drawer=new std::vector<int>; m_tree->Branch("TILE_murcv_digit_drawer",&TILE_murcv_digit_drawer);
  TILE_murcv_digit_channel=new std::vector<int>; m_tree->Branch("TILE_murcv_digit_channel",&TILE_murcv_digit_channel);
  TILE_murcv_digit_sampleVec=new std::vector<std::vector<float>>; m_tree->Branch("TILE_murcv_digit_sampleVec",&TILE_murcv_digit_sampleVec);

  //TGC Coin Data
  m_tree->Branch("tgc_coin_n",&tgc_coin_n,"tgc_coin_n/I");
  tgc_coin_x_In=new std::vector<float>; m_tree->Branch("tgc_coin_x_In",&tgc_coin_x_In);
  tgc_coin_y_In=new std::vector<float>; m_tree->Branch("tgc_coin_y_In",&tgc_coin_y_In);
  tgc_coin_z_In=new std::vector<float>; m_tree->Branch("tgc_coin_z_In",&tgc_coin_z_In);
  tgc_coin_x_Out=new std::vector<float>; m_tree->Branch("tgc_coin_x_Out",&tgc_coin_x_Out);
  tgc_coin_y_Out=new std::vector<float>; m_tree->Branch("tgc_coin_y_Out",&tgc_coin_y_Out);
  tgc_coin_z_Out=new std::vector<float>; m_tree->Branch("tgc_coin_z_Out",&tgc_coin_z_Out);
  tgc_coin_width_In=new std::vector<float>; m_tree->Branch("tgc_coin_width_In",&tgc_coin_width_In);
  tgc_coin_width_Out=new std::vector<float>; m_tree->Branch("tgc_coin_width_Out",&tgc_coin_width_Out);
  tgc_coin_width_R=new std::vector<float>; m_tree->Branch("tgc_coin_width_R",&tgc_coin_width_R);
  tgc_coin_width_Phi=new std::vector<float>; m_tree->Branch("tgc_coin_width_Phi",&tgc_coin_width_Phi);
  tgc_coin_isAside=new std::vector<int>; m_tree->Branch("tgc_coin_isAside",&tgc_coin_isAside);
  tgc_coin_isForward=new std::vector<int>; m_tree->Branch("tgc_coin_isForward",&tgc_coin_isForward);
  tgc_coin_isStrip=new std::vector<int>; m_tree->Branch("tgc_coin_isStrip",&tgc_coin_isStrip);
  tgc_coin_isInner=new std::vector<int>; m_tree->Branch("tgc_coin_isInner",&tgc_coin_isInner);
  tgc_coin_type=new std::vector<int>; m_tree->Branch("tgc_coin_type",&tgc_coin_type);
  tgc_coin_trackletId=new std::vector<int>; m_tree->Branch("tgc_coin_trackletId",&tgc_coin_trackletId);
  tgc_coin_trackletIdStrip=new std::vector<int>; m_tree->Branch("tgc_coin_trackletIdStrip",&tgc_coin_trackletIdStrip);
  tgc_coin_phi=new std::vector<int>; m_tree->Branch("tgc_coin_phi",&tgc_coin_phi);
  tgc_coin_roi=new std::vector<int>; m_tree->Branch("tgc_coin_roi",&tgc_coin_roi);
  tgc_coin_pt=new std::vector<int>; m_tree->Branch("tgc_coin_pt",&tgc_coin_pt);
  tgc_coin_delta=new std::vector<int>; m_tree->Branch("tgc_coin_delta",&tgc_coin_delta);
  tgc_coin_sub=new std::vector<int>; m_tree->Branch("tgc_coin_sub",&tgc_coin_sub);
  tgc_coin_veto=new std::vector<int>; m_tree->Branch("tgc_coin_veto",&tgc_coin_veto);
  tgc_coin_bunch=new std::vector<int>; m_tree->Branch("tgc_coin_bunch",&tgc_coin_bunch);
  tgc_coin_inner=new std::vector<int>; m_tree->Branch("tgc_coin_inner",&tgc_coin_inner);

  //RoI
  m_tree->Branch("muctpi_ndatawords",&muctpi_ndatawords,"muctpi_ndatawords/I");
  muctpi_eta=new std::vector<float>; m_tree->Branch("muctpi_eta",&muctpi_eta);
  muctpi_phi=new std::vector<float>; m_tree->Branch("muctpi_phi",&muctpi_phi);
  muctpi_source=new std::vector<short>; m_tree->Branch("muctpi_source",&muctpi_source);
  muctpi_hemisphere=new std::vector<short>; m_tree->Branch("muctpi_hemisphere",&muctpi_hemisphere);
  muctpi_bcid=new std::vector<short>; m_tree->Branch("muctpi_bcid",&muctpi_bcid);
  muctpi_sectorID=new std::vector<short>; m_tree->Branch("muctpi_sectorID",&muctpi_sectorID);
  muctpi_thrNumber=new std::vector<short>; m_tree->Branch("muctpi_thrNumber",&muctpi_thrNumber);
  muctpi_roi=new std::vector<short>; m_tree->Branch("muctpi_roi",&muctpi_roi);
  muctpi_veto=new std::vector<short>; m_tree->Branch("muctpi_veto",&muctpi_veto);
  muctpi_charge=new std::vector<short>; m_tree->Branch("muctpi_charge",&muctpi_charge);
  muctpi_candidateVetoed=new std::vector<short>; m_tree->Branch("muctpi_candidateVetoed",&muctpi_candidateVetoed);

  //HLT
  m_tree->Branch("HLT_info_n",&HLT_info_n,"HLT_info_n/I");
  HLT_info_chain=new std::vector<std::string>; m_tree->Branch("HLT_info_chain",&HLT_info_chain);
  HLT_info_isPassed=new std::vector<int>; m_tree->Branch("HLT_info_isPassed",&HLT_info_isPassed);
  HLT_info_typeVec=new std::vector<std::vector<int>>; m_tree->Branch("HLT_info_typeVec",&HLT_info_typeVec);
  HLT_info_ptVec=new std::vector<std::vector<float>>; m_tree->Branch("HLT_info_ptVec",&HLT_info_ptVec);
  HLT_info_etaVec=new std::vector<std::vector<float>>; m_tree->Branch("HLT_info_etaVec",&HLT_info_etaVec);
  HLT_info_phiVec=new std::vector<std::vector<float>>; m_tree->Branch("HLT_info_phiVec",&HLT_info_phiVec);

  //Truth
  m_tree->Branch("mc_n",&mc_n,"mc_n/I");
  mc_pt=new std::vector<float>; m_tree->Branch("mc_pt",&mc_pt);
  mc_eta=new std::vector<float>; m_tree->Branch("mc_eta",&mc_eta);
  mc_phi=new std::vector<float>; m_tree->Branch("mc_phi",&mc_phi);
  mc_m=new std::vector<float>; m_tree->Branch("mc_m",&mc_m);
  mc_charge=new std::vector<int>; m_tree->Branch("mc_charge",&mc_charge);

  //Run-3
  m_tree->Branch("TGC_Run3_n",&TGC_Run3_n,"TGC_Run3_n/I");
  TGC_Run3_pt=new std::vector<int>; m_tree->Branch("TGC_Run3_pt",&TGC_Run3_pt);
  TGC_Run3_type=new std::vector<int>; m_tree->Branch("TGC_Run3_type",&TGC_Run3_type);
  TGC_Run3_station=new std::vector<int>; m_tree->Branch("TGC_Run3_station",&TGC_Run3_station);
  TGC_Run3_DR=new std::vector<int>; m_tree->Branch("TGC_Run3_DR",&TGC_Run3_DR);
  TGC_Run3_DPhi=new std::vector<int>; m_tree->Branch("TGC_Run3_DPhi",&TGC_Run3_DPhi);
  TGC_Run3_TypeDPhi=new std::vector<int>; m_tree->Branch("TGC_Run3_TypeDPhi",&TGC_Run3_TypeDPhi);
  TGC_Run3_TypeDR=new std::vector<int>; m_tree->Branch("TGC_Run3_TypeDR",&TGC_Run3_TypeDR);
  TGC_Run3_Side=new std::vector<int>; m_tree->Branch("TGC_Run3_Side",&TGC_Run3_Side);
  TGC_Run3_RoI=new std::vector<int>; m_tree->Branch("TGC_Run3_RoI",&TGC_Run3_RoI);
  TGC_Run3_PhiSector=new std::vector<int>; m_tree->Branch("TGC_Run3_PhiSector",&TGC_Run3_PhiSector);
  TGC_Run3_IsEndcap=new std::vector<bool>; m_tree->Branch("TGC_Run3_IsEndcap",&TGC_Run3_IsEndcap);
  TGC_Run3_TrackletIdWire=new std::vector<int>; m_tree->Branch("TGC_Run3_TrackletIdWire",&TGC_Run3_TrackletIdWire);
  TGC_Run3_TrackletIdStrip=new std::vector<int>; m_tree->Branch("TGC_Run3_TrackletIdStrip",&TGC_Run3_TrackletIdStrip);
  TGC_Run3_x=new std::vector<float>; m_tree->Branch("TGC_Run3_x",&TGC_Run3_x);
  TGC_Run3_y=new std::vector<float>; m_tree->Branch("TGC_Run3_y",&TGC_Run3_y);
  TGC_Run3_z=new std::vector<float>; m_tree->Branch("TGC_Run3_z",&TGC_Run3_z);
  TGC_Run3_R=new std::vector<float>; m_tree->Branch("TGC_Run3_R",&TGC_Run3_R);
  TGC_Run3_Phi=new std::vector<float>; m_tree->Branch("TGC_Run3_Phi",&TGC_Run3_Phi);
  TGC_Run3_Charge=new std::vector<int>; m_tree->Branch("TGC_Run3_Charge",&TGC_Run3_Charge);
}

void HistogramManager::Clear(){
    muon_pt->clear();
    muon_phi->clear();
    muon_eta->clear();
    muon_m->clear();
    muon_author->clear();
    muon_charge->clear();
    muon_Type->clear();
    museg_x->clear();
    museg_y->clear();
    museg_z->clear();
    museg_px->clear();
    museg_py->clear();
    museg_pz->clear();
    museg_t0->clear();
    museg_t0error->clear();
    museg_chi2->clear();
    museg_ndof->clear();
    museg_sector->clear();
    museg_stationName->clear();
    museg_stationEta->clear();
    museg_author->clear();
    ext_mu_type->clear();
    ext_mu_index->clear();
    ext_mu_size->clear();
    ext_mu_targetVec->clear();
    ext_mu_targetDistanceVec->clear();
    ext_mu_targetEtaVec->clear();
    ext_mu_targetPhiVec->clear();
    ext_mu_targetDeltaEtaVec->clear();
    ext_mu_targetDeltaPhiVec->clear();
    ext_mu_targetPxVec->clear();
    ext_mu_targetPyVec->clear();
    ext_mu_targetPzVec->clear();
    TGC_prd_x->clear();
    TGC_prd_y->clear();
    TGC_prd_z->clear();
    TGC_prd_shortWidth->clear();
    TGC_prd_longWidth->clear();
    TGC_prd_length->clear();
    TGC_prd_isStrip->clear();
    TGC_prd_gasGap->clear();
    TGC_prd_channel->clear();
    TGC_prd_eta->clear();
    TGC_prd_phi->clear();
    TGC_prd_station->clear();
    TGC_prd_bunch->clear();
    RPC_prd_x->clear();
    RPC_prd_y->clear();
    RPC_prd_z->clear();
    RPC_prd_x2->clear();
    RPC_prd_y2->clear();
    RPC_prd_z2->clear();
    RPC_prd_time->clear();
    RPC_prd_triggerInfo->clear();
    RPC_prd_ambiguityFlag->clear();
    RPC_prd_measuresPhi->clear();
    RPC_prd_inRibs->clear();
    RPC_prd_station->clear();
    RPC_prd_stationEta->clear();
    RPC_prd_stationPhi->clear();
    RPC_prd_doubletR->clear();
    RPC_prd_doubletZ->clear();
    RPC_prd_stripWidth->clear();
    RPC_prd_stripLength->clear();
    RPC_prd_gasGap->clear();
    RPC_prd_channel->clear();
    tgc_coin_x_In->clear();
    tgc_coin_y_In->clear();
    tgc_coin_z_In->clear();
    tgc_coin_x_Out->clear();
    tgc_coin_y_Out->clear();
    tgc_coin_z_Out->clear();
    tgc_coin_width_In->clear();
    tgc_coin_width_Out->clear();
    tgc_coin_width_R->clear();
    tgc_coin_width_Phi->clear();
    tgc_coin_isAside->clear();
    tgc_coin_isStrip->clear();
    tgc_coin_isForward->clear();
    tgc_coin_isInner->clear();
    tgc_coin_type->clear();
    tgc_coin_trackletId->clear();
    tgc_coin_trackletIdStrip->clear();
    tgc_coin_phi->clear();
    tgc_coin_roi->clear();
    tgc_coin_pt->clear();
    tgc_coin_delta->clear();
    tgc_coin_sub->clear();
    tgc_coin_veto->clear();
    tgc_coin_bunch->clear();
    tgc_coin_inner->clear();
    TILE_murcv_trig_mod->clear();
    TILE_murcv_trig_part->clear();
    TILE_murcv_trig_bit0->clear();
    TILE_murcv_trig_bit1->clear();
    TILE_murcv_trig_bit2->clear();
    TILE_murcv_trig_bit3->clear();
    TILE_murcv_raw_count->clear();
    TILE_murcv_raw_energy->clear();
    TILE_murcv_raw_ros->clear();
    TILE_murcv_raw_drawer->clear();
    TILE_murcv_raw_channel->clear();
    TILE_murcv_digit_nSamples->clear();
    TILE_murcv_digit_ros->clear();
    TILE_murcv_digit_drawer->clear();
    TILE_murcv_digit_channel->clear();
    TILE_murcv_digit_sampleVec->clear();
    muctpi_eta->clear();
    muctpi_phi->clear();
    muctpi_source->clear();
    muctpi_hemisphere->clear();
    muctpi_bcid->clear();
    muctpi_sectorID->clear();
    muctpi_thrNumber->clear();
    muctpi_roi->clear();
    muctpi_veto->clear();
    muctpi_charge->clear();
    muctpi_candidateVetoed->clear();
    HLT_info_chain->clear();
    HLT_info_isPassed->clear();
    HLT_info_typeVec->clear();
    HLT_info_ptVec->clear();
    HLT_info_etaVec->clear();
    HLT_info_phiVec->clear();
    mc_pt->clear();
    mc_eta->clear();
    mc_phi->clear();
    mc_m->clear();
    mc_charge->clear();
    TGC_Run3_pt->clear();
    TGC_Run3_type->clear();
    TGC_Run3_station->clear();
    TGC_Run3_DR->clear();
    TGC_Run3_DPhi->clear();
    TGC_Run3_TypeDPhi->clear();
    TGC_Run3_TypeDR->clear();
    TGC_Run3_Side->clear();
    TGC_Run3_RoI->clear();
    TGC_Run3_PhiSector->clear();
    TGC_Run3_IsEndcap->clear();
    TGC_Run3_TrackletIdWire->clear();
    TGC_Run3_TrackletIdStrip->clear();
    TGC_Run3_x->clear();
    TGC_Run3_y->clear();
    TGC_Run3_z->clear();
    TGC_Run3_R->clear();
    TGC_Run3_Phi->clear();
    TGC_Run3_Charge->clear();
    std::cout<<"a"<<std::endl;
}


HistogramManager::~HistogramManager(){
    delete muon_pt; muon_pt=0;
    delete muon_eta; muon_eta=0;
    delete muon_phi; muon_phi=0;
    delete muon_m; muon_m=0;
    delete muon_charge; muon_charge=0;
    delete muon_author; muon_author=0;
    delete muon_Type; muon_Type=0;
    delete museg_x; museg_x=0;
    delete museg_y; museg_y=0;
    delete museg_z; museg_z=0;
    delete museg_px; museg_px=0;
    delete museg_py; museg_py=0;
    delete museg_pz; museg_pz=0;
    delete museg_t0; museg_t0=0;
    delete museg_t0error; museg_t0error=0;
    delete museg_chi2; museg_chi2=0;
    delete museg_ndof; museg_ndof=0;
    delete museg_sector; museg_sector=0;
    delete museg_stationName; museg_stationName=0;
    delete museg_stationEta; museg_stationEta=0;
    delete museg_author; museg_author=0;
    delete ext_mu_type; ext_mu_type=0;
    delete ext_mu_index; ext_mu_index=0;
    delete ext_mu_size; ext_mu_size=0;
    delete ext_mu_targetVec; ext_mu_targetVec=0;
    delete ext_mu_targetDistanceVec; ext_mu_targetDistanceVec=0;
    delete ext_mu_targetEtaVec; ext_mu_targetEtaVec=0;
    delete ext_mu_targetPhiVec; ext_mu_targetPhiVec=0;
    delete ext_mu_targetDeltaEtaVec; ext_mu_targetDeltaEtaVec=0;
    delete ext_mu_targetDeltaPhiVec; ext_mu_targetDeltaPhiVec=0;
    delete ext_mu_targetPxVec; ext_mu_targetPxVec=0;
    delete ext_mu_targetPyVec; ext_mu_targetPyVec=0;
    delete ext_mu_targetPzVec; ext_mu_targetPzVec=0;
    delete TGC_prd_x; TGC_prd_x=0;
    delete TGC_prd_y; TGC_prd_y=0;
    delete TGC_prd_z; TGC_prd_z=0;
    delete TGC_prd_shortWidth; TGC_prd_shortWidth=0;
    delete TGC_prd_longWidth; TGC_prd_longWidth=0;
    delete TGC_prd_length; TGC_prd_length=0;
    delete TGC_prd_isStrip; TGC_prd_isStrip=0;
    delete TGC_prd_gasGap; TGC_prd_gasGap=0;
    delete TGC_prd_channel; TGC_prd_channel=0;
    delete TGC_prd_eta; TGC_prd_eta=0;
    delete TGC_prd_phi; TGC_prd_phi=0;
    delete TGC_prd_station; TGC_prd_station=0;
    delete TGC_prd_bunch; TGC_prd_bunch=0;
    delete RPC_prd_x; RPC_prd_x=0;
    delete RPC_prd_y; RPC_prd_y=0;
    delete RPC_prd_z; RPC_prd_z=0;
    delete RPC_prd_x2; RPC_prd_x2=0;
    delete RPC_prd_y2; RPC_prd_y2=0;
    delete RPC_prd_z2; RPC_prd_z2=0;
    delete RPC_prd_time; RPC_prd_time=0;
    delete RPC_prd_triggerInfo; RPC_prd_triggerInfo=0;
    delete RPC_prd_ambiguityFlag; RPC_prd_ambiguityFlag=0;
    delete RPC_prd_measuresPhi; RPC_prd_measuresPhi=0;
    delete RPC_prd_inRibs; RPC_prd_inRibs=0;
    delete RPC_prd_station; RPC_prd_station=0;
    delete RPC_prd_stationEta; RPC_prd_stationEta=0;
    delete RPC_prd_stationPhi; RPC_prd_stationPhi=0;
    delete RPC_prd_doubletR; RPC_prd_doubletR=0;
    delete RPC_prd_doubletZ; RPC_prd_doubletZ=0;
    delete RPC_prd_stripWidth; RPC_prd_stripWidth=0;
    delete RPC_prd_stripLength; RPC_prd_stripLength=0;
    delete RPC_prd_gasGap; RPC_prd_gasGap=0;
    delete RPC_prd_channel; RPC_prd_channel=0;
    delete tgc_coin_x_In; tgc_coin_x_In=0;
    delete tgc_coin_y_In; tgc_coin_y_In=0;
    delete tgc_coin_z_In; tgc_coin_z_In=0;
    delete tgc_coin_x_Out; tgc_coin_x_Out=0;
    delete tgc_coin_y_Out; tgc_coin_y_Out=0;
    delete tgc_coin_z_Out; tgc_coin_z_Out=0;
    delete tgc_coin_width_In; tgc_coin_width_In=0;
    delete tgc_coin_width_Out; tgc_coin_width_Out=0;
    delete tgc_coin_width_R; tgc_coin_width_R=0;
    delete tgc_coin_width_Phi; tgc_coin_width_Phi=0;
    delete tgc_coin_isAside; tgc_coin_isAside=0;
    delete tgc_coin_isForward; tgc_coin_isForward=0;
    delete tgc_coin_isStrip; tgc_coin_isStrip=0;
    delete tgc_coin_isInner; tgc_coin_isInner=0;
    delete tgc_coin_type; tgc_coin_type=0;
    delete tgc_coin_trackletId; tgc_coin_trackletId=0;
    delete tgc_coin_trackletIdStrip; tgc_coin_trackletIdStrip=0;
    delete tgc_coin_phi; tgc_coin_phi=0;
    delete tgc_coin_pt; tgc_coin_pt=0;
    delete tgc_coin_delta; tgc_coin_delta=0;
    delete tgc_coin_sub; tgc_coin_sub=0;
    delete tgc_coin_veto; tgc_coin_veto=0;
    delete tgc_coin_bunch; tgc_coin_bunch=0;
    delete tgc_coin_inner; tgc_coin_inner=0;
    delete TILE_murcv_trig_mod; TILE_murcv_trig_mod=0;
    delete TILE_murcv_trig_part; TILE_murcv_trig_part=0;
    delete TILE_murcv_trig_bit0; TILE_murcv_trig_bit0=0;
    delete TILE_murcv_trig_bit1; TILE_murcv_trig_bit1=0;
    delete TILE_murcv_trig_bit2; TILE_murcv_trig_bit2=0;
    delete TILE_murcv_trig_bit3; TILE_murcv_trig_bit3=0;
    delete TILE_murcv_raw_count; TILE_murcv_raw_count=0;
    delete TILE_murcv_raw_energy; TILE_murcv_raw_energy=0;
    delete TILE_murcv_raw_ros; TILE_murcv_raw_ros=0;
    delete TILE_murcv_raw_drawer; TILE_murcv_raw_drawer=0;
    delete TILE_murcv_raw_channel; TILE_murcv_raw_channel=0;
    delete TILE_murcv_digit_nSamples; TILE_murcv_digit_nSamples=0;
    delete TILE_murcv_digit_ros; TILE_murcv_digit_ros=0;
    delete TILE_murcv_digit_drawer; TILE_murcv_digit_drawer=0;
    delete TILE_murcv_digit_channel; TILE_murcv_digit_channel=0;
    delete TILE_murcv_digit_sampleVec; TILE_murcv_digit_sampleVec=0;
    delete muctpi_eta; muctpi_eta=0;
    delete muctpi_phi; muctpi_phi=0;
    delete muctpi_source; muctpi_source=0;
    delete muctpi_hemisphere; muctpi_hemisphere=0;
    delete muctpi_bcid; muctpi_bcid=0;
    delete muctpi_sectorID; muctpi_sectorID=0;
    delete muctpi_thrNumber; muctpi_thrNumber=0;
    delete muctpi_roi; muctpi_roi=0;
    delete muctpi_veto; muctpi_veto=0;
    delete muctpi_charge; muctpi_charge=0;
    delete muctpi_candidateVetoed; muctpi_candidateVetoed=0;   
    delete HLT_info_chain; HLT_info_chain=0;
    delete HLT_info_isPassed; HLT_info_isPassed=0;
    delete HLT_info_typeVec; HLT_info_typeVec=0;
    delete HLT_info_ptVec; HLT_info_ptVec=0;
    delete HLT_info_etaVec; HLT_info_etaVec=0;
    delete HLT_info_phiVec; HLT_info_phiVec=0;
    delete mc_pt; mc_pt=0;
    delete mc_eta; mc_eta=0;
    delete mc_phi; mc_phi=0;
    delete mc_m; mc_m=0;
    delete mc_charge; mc_charge=0;
    delete TGC_Run3_pt; TGC_Run3_pt=0;
    delete TGC_Run3_type; TGC_Run3_type=0;
    delete TGC_Run3_station; TGC_Run3_station=0;
    delete TGC_Run3_DR; TGC_Run3_DR=0;
    delete TGC_Run3_DPhi; TGC_Run3_DPhi=0;
    delete TGC_Run3_TypeDPhi; TGC_Run3_TypeDPhi=0;
    delete TGC_Run3_TypeDR; TGC_Run3_TypeDR=0;
    delete TGC_Run3_Side; TGC_Run3_Side=0;
    delete TGC_Run3_RoI; TGC_Run3_RoI=0;
    delete TGC_Run3_PhiSector; TGC_Run3_PhiSector=0;
    delete TGC_Run3_IsEndcap; TGC_Run3_IsEndcap=0;
    delete TGC_Run3_TrackletIdWire; TGC_Run3_TrackletIdWire=0;
    delete TGC_Run3_TrackletIdStrip; TGC_Run3_TrackletIdStrip=0;
    delete TGC_Run3_x; TGC_Run3_x=0;
    delete TGC_Run3_y; TGC_Run3_y=0;
    delete TGC_Run3_z; TGC_Run3_z=0;
    delete TGC_Run3_R; TGC_Run3_R=0;
    delete TGC_Run3_Phi; TGC_Run3_Phi=0;
    delete TGC_Run3_Charge; TGC_Run3_Charge=0;

  file->Write();
  file->Close();
  std::cout<<"*************** FILE SAVED ****************"<<std::endl;
}
